import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Banknote,
  Bold,
  Book,
  BookKey,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseConveyorBelt,
  Building,
  Calendar,
  CalendarIcon,
  Car,
  CarFront,
  Check,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  ClipboardPenLine,
  Command,
  Droplet,
  Clock,
  Eye,
  EyeOff,
  File,
  FileDigit,
  FilePlus2,
  FileQuestion,
  FileWarning,
  Folder,
  Frown,
  Fuel,
  GalleryVerticalEnd,
  Gauge,
  Hammer,
  Handshake,
  Home,
  Hourglass,
  IdCard,
  Import,
  Inbox,
  Info,
  Italic,
  KeyRound,
  LayoutGrid,
  Layers,
  Link,
  Link2,
  RefreshCcw,
  List,
  ListOrdered,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MapPin,
  MapPinCheckInside,
  Menu,
  MessageSquareMore,
  Package,
  PaintBucket,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Plus,
  ScrollText,
  Search,
  Send,
  Settings,
  Settings2,
  ShoppingBag,
  SquareTerminal,
  Strikethrough,
  Trash2,
  Truck,
  Underline,
  User,
  Users,
  Wrench,
  X,
  Hash,
  Star,
} from "lucide-react";

export const icons = {
  Star,
  refreshCcw: RefreshCcw,
  hourglass: Hourglass,
  hash: Hash,
  import: Import,
  search: Search,
  clipboardList: ClipboardList,
  filePlus: FilePlus2,
  handhake: Handshake,
  briefcase: BriefcaseConveyorBelt,
  settings: Settings,
  clock: Clock,
  inbox: Inbox,
  calendarIcon: CalendarIcon,
  gallery: GalleryVerticalEnd,
  audio: AudioWaveform,
  command: Command,
  square: SquareTerminal,
  bot: Bot,
  bookOpen: BookOpen,
  settings2: Settings2,
  logout: LogOut,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignRight: AlignRight,
  listOrdered: ListOrdered,
  lockOpen: LockOpen,
  lock: Lock,
  archive: Archive,
  circleCheck: CircleCheck,
  file: File,
  fileDigit: FileDigit,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  link: Link,
  pin: MapPin,
  bookKey: BookKey,
  email: Mail,
  link2: Link2,
  clipboard: ClipboardPenLine,
  gas: Fuel,
  clean: Droplet,
  gauge: Gauge,
  pinCheck: MapPinCheckInside,
  eye: Eye,
  eyeOff: EyeOff,
  key: KeyRound,
  plus: Plus,
  user: User,
  users: Users,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  check: Check,
  pencil: Pencil,
  home: Home,
  list: List,
  menu: Menu,
  x: X,
  trash: Trash2,
  calendar: Calendar,
  boxes: Boxes,
  message: MessageSquareMore,
  package: Package,
  shoppingBag: ShoppingBag,
  wrench: Wrench,
  truck: Truck,
  banknote: Banknote,
  fileQuestion: FileQuestion,
  fileWarning: FileWarning,
  phone: Phone,
  LayoutGrid,
  Layers,
  building: Building,
  hammer: Hammer,
  frown: Frown,
  paperclip: Paperclip,
  folder: Folder,
  idCard: IdCard,
  info: Info,
  book: Book,
  circleHelp: CircleHelp,
  car: Car,
  carFront: CarFront,
  paintBucket: PaintBucket,
  scrollText: ScrollText,
  chevronsUpDown: ChevronsUpDown,
  pause: Pause,
  send: Send,
};

export type IIcons = keyof typeof icons;
